CREATE TABLE USUARIO (
  ID_USUARIO INTEGER AUTO_INCREMENT NOT NULL,
  LOGIN_USUARIO VARCHAR(15) NOT NULL,
  SENHA_USUARIO VARCHAR(20) NOT NULL,
  NOME_USUARIO  VARCHAR(50) NOT NULL,
  EMAIL_USUARIO VARCHAR(60) NOT NULL,
  TELEFONE_USUARIO VARCHAR(15),
  CONSTRAINT PRIMARY KEY (ID_USUARIO)
);

CREATE TABLE  EVENTO (
  ID_EVENTO INTEGER AUTO_INCREMENT NOT NULL,
  NOME_EVENTO VARCHAR(30),
  LOCAL_EVENTO VARCHAR (50),
  DESCRICAO_EVENTO VARCHAR(150),
  HORA_INICIO_EVENTO DATE,
  HORA_FIM_EVENTO DATE,
  IDF_USUARIO INTEGER NOT NULL,
  CONSTRAINT PRIMARY KEY (ID_EVENTO)
);

ALTER TABLE EVENTO ADD CONSTRAINT FK_ID_USUARIO
FOREIGN KEY (IDF_USUARIO) REFERENCES USUARIO (ID_USUARIO);